openapi: 3.0.0
info:
  title: Authentication API
  description: API cung cấp các chức năng xác thực người dùng như đăng nhập, đăng ký, quên mật khẩu, xác thực tài khoản.
  version: 1.0.0

paths:
  /auth/login:
    post:
      summary: Đăng nhập
      description: Người dùng nhập email và mật khẩu để đăng nhập vào hệ thống.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                password:
                  type: string
                  format: password
                  example: "12345678"
      responses:
        "200":
          description: Đăng nhập thành công, trả về access token, refresh token và thông tin người dùng.
          content:
            application/json:
              schema:
                type: object
                properties:
                  access_token:
                    type: string
                    example: "eyJhbGciOiJIUzI1Ni..."
                  refresh_token:
                    type: string
                    example: "eyJhbGciOiJIUzI1Ni..."
                  user:
                    $ref: "#/components/schemas/User"
        "400":
          description: Thông tin không hợp lệ (thiếu email hoặc mật khẩu, sai định dạng email, v.v.)
        "401":
          description: Sai email hoặc mật khẩu
        "404":
          description: Người dùng không tồn tại
        "500":
          description: Lỗi server

  /auth/logout:
    post:
      summary: Đăng xuất
      description: Người dùng đăng xuất khỏi hệ thống, làm mất hiệu lực refresh token.
      security:
        - BearerAuth: []
      responses:
        "200":
          description: Đăng xuất thành công
        "401":
          description: Không có quyền truy cập
        "500":
          description: Lỗi server

  /auth/forgot-password:
    post:
      summary: Quên mật khẩu
      description: Gửi email đặt lại mật khẩu.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
              properties:
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
      responses:
        "200":
          description: Email đặt lại mật khẩu đã được gửi
        "400":
          description: Email không hợp lệ
        "500":
          description: Lỗi server

  /auth/verify-code:
    post:
      summary: Xác thực mã OTP
      description: Xác thực mã OTP khi đặt lại mật khẩu.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - code
              properties:
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                code:
                  type: string
                  example: "123456"
      responses:
        "200":
          description: Mã xác thực hợp lệ
        "400":
          description: Mã không hợp lệ hoặc hết hạn
        "500":
          description: Lỗi server

  /auth/change-password:
    post:
      summary: Thay đổi mật khẩu
      description: Đổi mật khẩu mới sau khi xác thực mã OTP.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - newPassword
              properties:
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                newPassword:
                  type: string
                  format: password
                  example: "newpassword123"
      responses:
        "200":
          description: Thay đổi mật khẩu thành công
        "400":
          description: Mật khẩu không hợp lệ
        "500":
          description: Lỗi server

  /auth/verify-account:
    post:
      summary: Xác thực tài khoản
      description: Người dùng xác thực tài khoản sau khi đăng ký bằng mã OTP.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - code
              properties:
                email:
                  type: string
                  format: email
                  example: johndoe@example.com
                code:
                  type: string
                  example: "123456"
      responses:
        "200":
          description: Tài khoản đã được xác thực thành công
        "400":
          description: Mã không hợp lệ hoặc đã hết hạn
        "500":
          description: Lỗi server

components:
  schemas:
    User:
      type: object
      description: Thông tin người dùng
      properties:
        user_id:
          type: integer
          example: 1
        fullname:
          type: string
          example: John Doe
        email:
          type: string
          format: email
          example: johndoe@example.com
        isAdmin:
          type: boolean
          example: false

  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
